# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UiCGsKNOsW5y_1GlgXZb2zcC4k7GM9Sr
"""

def test_demo():
  print('Funzt')